name: project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  file_picker: ^6.1.0
  image_picker: ^1.1.2
  fl_chart: ^0.68.0

  # ✅ Use the GitHub version of charts_flutter (fixed for Flutter 3.7+)
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
dependency_overrides:
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter
      ref: master


flutter:
  uses-material-design: true

  assets:
    - assets/images/spacyn_logo.png
    - assets/images/post1.jpg
    - assets/images/post2.jpg
    - assets/images/post3.jpg
    - assets/images/profile.jpg
